
title: Harlist
description: Marketing site for https://www.harlist.io
baseurl: ""
url: ""

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor
  - gulpfile.js
  - package.json
  - README.md
  - yarn.lock
